version: '3'
services:

  #PHP Service
  apache_php:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    image: digitalocean.com/php
    container_name: ${DOCKER_PREFIX}-apache_php
    restart: unless-stopped
    tty: true
    depends_on:
      - db
    environment:
      SERVICE_NAME: apache_php
      SERVICE_TAGS: dev
    working_dir: /var/www
    user: "1000:1000"
    volumes:
      - ./app:/var/www
      - ./docker/php-fpm/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/php-fpm/supervisor-workers.conf:/etc/supervisor/conf.d/supervisor-workers.conf
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:8.0.15
    container_name: ${DOCKER_PREFIX}-db
    restart: unless-stopped
    tty: true
    command:
      --default-authentication-plugin=mysql_native_password
      --performance-schema --secure-file-priv=""

      #--bash -c "mysqld --user=root --group_concat_max_len=1844674407370954752"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${DOCKER_PREFIX}-phpmyadmin
    links: 
      - db:db
    ports:
      - 8765:80
    environment:
      # MYSQL_USER: ${DB_USER}
      # MYSQL_PASSWORD: ${DB_PASSWORD}
      # MYSQL_ROOT_PASSWORD: toor
      PMA_ARBITRARY: 1
    restart: always

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: ${DOCKER_PREFIX}-nginx
    restart: unless-stopped
    tty: true
    depends_on:
      - apache_php
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www
      - ./docker/nginx/local.conf:/etc/nginx/conf.d/default.conf

      - /etc/letsencrypt:/etc/letsencrypt/live/laravel.loc/
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
